apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.21.0
          ports:
            - containerPort: 9090
              name: http
