apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: file-server
spec:
  selector:
    app: file-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      name: file-server
      labels:
        app: file-server
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      volumes:
        - name: consul-extensions
          persistentVolumeClaim:
            claimName: consul-extensions
            readOnly: true
      containers:
        - name: file-server
          image: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: consul-extensions
              mountPath: /usr/share/nginx/html
              readOnly: true
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: file-server
