apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: api
    namespace: default
  sources:
    - name: web
      namespace: default
      permissions:
        - action: allow
          http:
            pathPrefix: '/'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: file-server
spec:
  destination:
    name: file-server
    namespace: default
  sources:
    - name: api
      namespace: default
      permissions:
        - action: allow
          http:
            pathPrefix: '/'
    - name: pci-backend-db
      namespace: pci-backend
      permissions:
        - action: allow
          http:
            pathPrefix: '/'
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: pci-backend-db
  namespace: pci-backend
spec:
  destination:
    name: pci-backend-db
    namespace: pci-backend
  sources:
    - name: pci-frontend-web
      namespace: pci-frontend
      permissions:
        - action: allow
          http:
            pathPrefix: '/'
