apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: pci-backend-db
spec:
  selector:
    app: pci-backend-db
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pci-backend-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pci-backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pci-backend-db
  template:
    metadata:
      name: pci-backend-db
      labels:
        app: pci-backend-db
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      serviceAccountName: pci-backend-db
      containers:
        - name: pci-backend-db
          image: nicholasjackson/fake-service:v0.21.0
          ports:
            - containerPort: 9090
              name: http
        - name: opa
          image: openpolicyagent/opa:0.53.0-envoy-3
          args:
            - "run"
            - "--server"
            - "--config-file=/etc/opa/config.yaml"
            - "--addr=localhost:8181"
            - "--diagnostic-addr=0.0.0.0:8282"
            - "--ignore=.*"
            - "/consul-extensions/pci.rego"
          volumeMounts:
            - name: opa-policy
              mountPath: /consul-extensions
              readOnly: true
            - name: opa-config
              mountPath: /etc/opa
              readOnly: true
      volumes:
        - name: opa-policy
          configMap:
            name: opa-policy
        - name: opa-config
          configMap:
            name: opa-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: envoy/authz/allow
    decision_logs:
      console: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
data:
  pci.rego: |
    package envoy.authz

    import future.keywords
    
    import input.attributes.request.http as http_request
    import input.attributes.metadata_context.filter_metadata.consul as consul

    default allow := false

    allow {
      permit
    }

    permit {
      consul.namespace == "pci-frontend"
    }

    permit {
      consul.namespace == "pci-backend"
    }
