apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-extensions
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/consul/extensions"