apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: pci-backend-db
  namespace: pci-backend
spec:
  protocol: http
  envoyExtensions:
  - name: builtin/ext-authz
    required: true
    arguments:
      Config:
        GrpcService:
          Target:
            URI: localhost:9191
